import { Geist, Geist_Mono } from "next/font/google";
import "./main.css";
import Header from "./components/Header";
// @ -> root folder (src folder)

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Next Routing",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        cz-shortcut-listen="true"
      >
        {/* <h4>This is form the root layout</h4> */}
        <Header />
        {children}
      </body>
    </html>
  );
}
